data_dir: /data/hkerner/geossl/SatCLIP_pretraining_data/satCLIP_continent_Samples/continent
batch_size: 256
num_workers: 8
crop_size: 256
val_random_split_fraction: 0.1
transform: pretrained
mode: both
_instantiator: lightning.pytorch.cli.instantiate_module
embed_dim: 256
image_resolution: 256
vision_layers: 4
vision_width: 128
vision_patch_size: 32
in_channels: 13
le_type: sphericalharmonics
pe_type: siren
frequency_num: 16
max_radius: 0.01
min_radius: 1.0e-05
legendre_polys: 32
harmonics_calculation: analytic
sh_embedding_dims: 32
learning_rate: 0.0001
weight_decay: 0.01
num_hidden_layers: 2
capacity: 256
